### ISSUE TITLE
Uploading original image in case there are no transformations applied

### ISSUE THREAD

**Issue by kasparek** [pqina/filepond-plugin-image-transform#1]
Trying to understand if there is a way to do that, but so far I did not have any luck.

I've noticed you implemented the upscale = false, to prevent upscaling images smaller than target size, which is one thing I was looking before.

But my next issues is I need to be able to upload original images without re-encoding into JPG again in case there are not transformations applied. Is that possible?

**Comment by kasparek** [comment]
The problem seems to be here:

// no transforms defined, we done!
if (quality === null && type === null && !crop && !transforms.length) {

where in transforms list there I have one transformation - resize - but since that is upscale=false, did not apply for my image, but is still in the list of transforms and the image is re-encoded

**Comment by kasparek** [comment]
One way easy to do I thought would be just compare the imagedata after the transform worker returns the response. If the imagedata are unchanged, you can upload the original image. Problem I found is that the original image does not seem to be stored anywhere.

**Comment by rikschennink** [comment]
That could work but I'm a bit worried comparing big ImageData objects might be too heavy on the CPU. 

A way to know if a transform should be applied or if it has already been applied ( suppose the file is loaded from the server and has already been compressed / filtered / watermarked / resized / etc. ) would be more flexible and faster. With server files the server could return some additional information with the file ( as a custom header maybe ), then each transform ( currently it's only the crop and resize plugins, but I'm planning to add more ) could expose a boolean indicating whether it should be applied or not.

**Comment by rikschennink** [comment]
@kasparek Just wanted to let you know that this is still on my radar but haven't gotten around to picking it up yet.

**Comment by kasparek** [comment]
Great, I was thinking creating additional plugin to sort of do verification
for necessity of each transformation. But would be probably better
implemented in transformer itself.

po 18. 6. 2018 v 14:08 odesílatel Rik <notifications@github.com> napsal:

**Comment by rikschennink** [comment]
It's tricky so I'm taking a bit of time to consider a good (future proof) approach, would hate to build something and have to make breaking changes later on.

**Comment by rikschennink** [comment]
Just wanted to let you know that it's still on my todo list, life has got in the way ;-)

**Comment by kasparek** [comment]
Great, this is really important for my case. Need to be able upload
prepared images from more advanced users without re-encoding, but also
scale big image directly from cameras.

čt 12. 7. 2018 v 7:43 odesílatel Rik <notifications@github.com> napsal:

**Comment by kasparek** [comment]
I am not sure I follow how do you mean to use that plugin for the given
problem. The images that need NOT to be re-encoded are not uploaded yet.

po 23. 7. 2018 v 7:23 odesílatel Rik <notifications@github.com> napsal:

**Comment by rikschennink** [comment]
Alright, I assumed this only concerned files uploaded by the user in an earlier session.

**Comment by rikschennink** [comment]
Can you try with this alpha version of the image resize plugin?
https://github.com/pqina/filepond-plugin-image-resize/tree/1.2.0-alpha

**Comment by kasparek** [comment]
Nope, did not help. Image still re-encoded even though I have set the
target image size bigger that the source image is. The uploaded image is
same size like the client uploading, but file size changes / so it is
re-encoded into new JPG.

út 24. 7. 2018 v 9:22 odesílatel Rik <notifications@github.com> napsal:

**Comment by rikschennink** [comment]
Okay, I’ll test this further when I get back from vacation in two weeks, had my fingers crossed that this was a quick fix to get it working.

**Comment by rikschennink** [comment]
Just got back and ran some tests. I missed some edge cases. I've added reading of image orientation and the resulting width height corrections plus corrections for `null` values in the `imageResizeTargetWidth` and `imageResizeTargetHeight` properties. Just published version `2.0.1` which contains these fixes, please let me know if this solves the problem on your side.

**Comment by kasparek** [comment]
Great, will test and let you know.

**Comment by kasparek** [comment]
So, I'm not sure if I'm doing something wrong, but the image when smaller than target size and upscale is false, is correctly not upscaled (is uploaded with same dimensions), but still re-encoded (the filesize is different). This is my configuration for filepond: 
FilePond.create(
  input,
  {
    imageTransformOutputQuality: 60,
    imagePreviewHeight: 270,
    imageResizeUpscale: false,
    imageResizeTargetWidth: 2190,
    imageResizeTargetHeight: 2190,
    imageResizeMode: 'contain'
  }
);

**Comment by rikschennink** [comment]
It gets re-encoded because the output quality parameter is set.

I'm going to add a bool that allows you to configure it to only apply quality to images when they require a transform.

**Comment by rikschennink** [comment]
I've just published version `2.1.0` adding the `imageTransformOutputQualityMode` option.

Set it to `'optional'` to only apply quality when resizing, cropping or changing file format.

**Comment by kasparek** [comment]
Great, that works.
