### ISSUE TITLE
preserve EXIF data fails since v3.4.0 (imageTransformOutputStripImageHead=false)

### ISSUE THREAD

**Issue by lukey78** [pqina/filepond-plugin-image-transform#13]
The plugin strips EXIF data from the image as of version 3.4.0, even with the option: `imageTransformOutputStripImageHead=false` 

I can confirm it is working with version 3.3.3, and stops working from 3.4.0 up to the current version.

See https://github.com/pqina/filepond/issues/250

**Comment by rikschennink** [comment]
@lukey78 Thanks for reporting, looking in to it now.

**Comment by rikschennink** [comment]
@lukey78 Fixed in `3.6.2`

**Comment by lukey78** [comment]
Thanks for the quick fix. Can confirm it's working!
