### ISSUE TITLE
Filename is lost after transform

### ISSUE THREAD

**Issue by rolandorojas** [pqina/filepond-plugin-image-transform#20]
### Description
When using the image transform plugin, the file name is replaced for the word "blob".

### Importance
In some instances, the original file name is required by the server. In my case, I am uploading product images that tie to a specific product using this name.

### How to reproduce

```
FilePond.create($refs.input, {
    imageResizeMode: 'contain',
    imageResizeTargetWidth: 1500,
    imageResizeTargetHeight: 1500,
    imageTransformOutputMimeType: 'image/jpeg',
    allowImageTransform: true,
});
```
Will produce a binary file upload with the following properties:

```
------WebKitFormBoundaryphp51Y8NEZqAWF1s
Content-Disposition: form-data; name="files[]"; filename="blob"
Content-Type: image/jpeg
...
```
_Notice the "blob" filename_. The original file name is now lost.

**Comment by rikschennink** [comment]
Are you uploading async using `server` prop, or using the file-encode plugin? Are you using a custom `server.process` method?

**Comment by rolandorojas** [comment]
I am using the `server.process` method to a sync upload the files. I am not using the file-encode plugin.

**Comment by rikschennink** [comment]
Are you using a custom process method or URL?

**Comment by rolandorojas** [comment]
Yes, I am using Laravel Livewire to side load the images as soon as they are selected. This process works perfectly unless I try to resize the image. 

Below is the exact code I am using. If I set `allowImageTransform` to `false` everything works. Otherwise, the file name is lost. 

```

FilePond.registerPlugin(FilePondPluginImageResize);
        FilePond.registerPlugin(FilePondPluginImageTransform);

        pond = FilePond.create($refs.input, {
            allowMultiple: true,
            imageResizeMode: 'contain',
            imageResizeTargetWidth: 1500,
            imageResizeTargetHeight: 1500,
            imageTransformOutputMimeType: 'image/jpeg',
            allowImageTransform: true,
            server: {
                process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
                    window.livewire.find('BnwoZyS7sjEJORZmqBFL').upload('images', file, load, error, progress)
                },
                revert: (filename, load) => {
                    window.livewire.find('BnwoZyS7sjEJORZmqBFL').removeUpload('images', filename, load)
                },
            },
        });
```

**Comment by rikschennink** [comment]
Can you try turning the `file` param into an actual file object.

```js
file = new File([file], file.name);
```
More info here: https://pqina.nl/blog/rename-a-file-with-javascript/

**Comment by rolandorojas** [comment]
Adding `new File([file], file.name);` solves the issue. Thanks!
