### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by freiand** [pqina/filepond-plugin-image-transform#25]
Would it be possible to add typescript support to this plugin? The other plugins (like FileEncode and ImageResize work fine).

I'm getting the error
`Cannot find module 'filepond-plugin-image-transform/dist' or its corresponding type declarations.`

for the line in app.module.ts

`import FilePondPluginImageTransform from "filepond-plugin-image-transform/dist";`

I'm on Angular 11.

**Comment by rikschennink** [comment]
Just added basic types and pushed to rpm so should work now.

**Comment by freiand** [comment]
Great! Thanks, @rikschennink
