### ISSUE TITLE
Request: Watermark to images

### ISSUE THREAD

**Issue by alewin** [pqina/filepond-plugin-image-transform#3]
I've seen that there are plugins for resizing and quality, I would need to apply a watermark, after having resized and lowered the quality of an image, can i use FilePond with another library like [watermarkjs](https://github.com/brianium/watermarkjs)?

Although the best solution would be to have a specific plugin for filepond... 

Thanks!

**Comment by rikschennink** [comment]
Hi @alewin, thanks for the suggestion. A watermark plugin is on my todolist but it's currently not in development as I'm busy building an image editor plugin first.

**Comment by alewin** [comment]
@rikschennink Oh ok If you need support I can look at it and make a merge request..

**Comment by rikschennink** [comment]
Thanks! I haven't yet uploaded the source files so pull requests on build targets are not super useful right now as they would be overwritten by a new build. Once the source files are up, any help is welcome. Will close for now, but rest assured its on the list. :-)

**Comment by rikschennink** [comment]
The demo on this page shows watermarking in action:
https://github.com/pqina/filepond-plugin-image-transform
