### ISSUE TITLE
Can we add webp?

### ISSUE THREAD

**Issue by bitdom8** [pqina/filepond-plugin-image-transform#33]
Need to make webp for faster reload? Right now, when I use this plugin, formdata doesn't read the converted file:

```
ondata: (formData) => {
						// const formData = new FormData();
						// formData.append('filepond', convertedwebp);

}
```

**Comment by rikschennink** [comment]
Please elaborate it's not clear what you want to achieve and what goes wrong. will close till updated. please leave comment when you've done so.

**Comment by bitdom8** [comment]
Hi Rik, thx for quick notice. Want to change the file format to webp. However file transform plugin doesn't let me. It interferes too much with formdata. I cant change it to webp

**Comment by rikschennink** [comment]
Not all browsers can output webp.

You'd have to either fork the image-transform-plugin or convert to webp in a custom process method.

**Comment by bitdom8** [comment]
Ach ok. But when I use image-transform-plugin, can't change formdata on the way

**Comment by bitdom8** [comment]
I mean this doesn't work:
```

// const formData = new FormData();
						// formData.append('filepond', convertedwebp);
```

**Comment by rikschennink** [comment]
It's commented and pseudo-code not sure what you expect from me. I'll leave this closed.
