### ISSUE TITLE
SVGs are converted to bitmaps

### ISSUE THREAD

**Issue by kylefox** [pqina/filepond-plugin-image-transform#4]
Hey, not sure if this is the intended behavior, but I discovered that SVGs are turned into bitmaps when transformed.

This totally makes sense, because you can't really resize or crop an SVG.

But I'm wondering if there could be an option for this, ex: `imageTransformSVGs`, which would default to `true` (backwards compatible) but could be set to `false` to leave SVGs as is.

Thoughts?

**Comment by rikschennink** [comment]
Hi @kylefox! Currently, they are transformed an converted, I'm planning to alter the transform plugin so it basically [alters the viewBox](https://stackoverflow.com/a/37589395/1774081) of the SVG resulting in a crop.

**Comment by kylefox** [comment]
Ah, neat idea. So it would leave SVGs as SVGs rather than convert to bitmap?

**Comment by rikschennink** [comment]
Indeed, I'm currently testing it, for now, it would only do cropping (not sure resizing is needed as SVGs are vector graphics, please let me know if that's not the case). It seems to work quite well.

**Comment by kylefox** [comment]
> not sure resizing is needed as SVGs are vector graphics

Yeah, exactly. No resize is necessary.

**Comment by rikschennink** [comment]
Just published version `2.0.1` of the FilePond core and version `2.0.0` of the image transform plugin which adds support for SVG cropping. 

I've tested it with a couple of SVGs (some with and some without size/viewport information) and it seems to function as intended. Let me know if you find any strange behavior.
