### ISSUE TITLE
Crop and resize to exact ratio

### ISSUE THREAD

**Issue by BenHarris** [pqina/filepond-plugin-image-transform#43]
I have read through all of the documentation and had a skim over the source code, but can't seem to find a solution to this. I'm not entirely clear if this question is more relevant to the crop, resize or transform plugin, so I hope it is ok for this to be posted here.

Is there a way to return an image that has a specific ratio by using padding instead of cropping? So the source image is basically resized as per the current functionality, but then padded to meet the ratio?

**Comment by rikschennink** [comment]
Hi, That's not possible with the image transform plugin. It does work with [Pintura](https://pqina.nl/pintura).

**Comment by BenHarris** [comment]
Thanks @rikschennink, Pintura looks good, although is definitely overkill for this use case. For what it's worth, it was pretty straightforward once I found the `imageTransformBeforeCreateBlob` hook:

```js
imageTransformBeforeCreateBlob: (canvas) => new Promise(resolve => {
    var image = new Image();
    image.src = canvas.toDataURL();
    image.onload = function(){
        canvas = document.createElement('canvas');
        canvas.width = 400;
        canvas.height = 300;

        var ctx = canvas.getContext('2d');
        var wrh = image.width / image.height;
        var newWidth = canvas.width;
        var newHeight = newWidth / wrh;
        if (newHeight > canvas.height) {
            newHeight = canvas.height;
            newWidth = newHeight * wrh;
        }
        var xOffset = newWidth < canvas.width ? ((canvas.width - newWidth) / 2) : 0;
        var yOffset = newHeight < canvas.height ? ((canvas.height - newHeight) / 2) : 0;

        ctx.drawImage(image, xOffset, yOffset, newWidth, newHeight);

        resolve(canvas);
    }
}),
```

**Comment by rikschennink** [comment]
Glad to see you found a workaround, thanks for sharing! 👍
