### ISSUE TITLE
Filesizes increases while image is (visually) not being transformed.

### ISSUE THREAD

**Issue by RenoLooijmans** [pqina/filepond-plugin-image-transform#44]
I have the following options enabled:

allowImageTransform: true,
imageTransformOutputQuality: 20,
imageTransformOutputQualityMode: 'optional',
allowImageResize: true,
allowImageCrop: true,
imageResizeMode: 'cover',
// some other values

When I upload a PNG file of filesize 1.73MB, which is exactly the given size (and thus no transform is applied, I assume), it ends up being around 2.1MB Chrome and 2.2MB in Firefox.

Changing the imageTransformOutputQuality does not seem to result in any changes in filesize or image quality.

Please note the image in question is compressed in Photoshop using the option 'slowest/smallest'.

See https://renolooijmans.nl/public/file_example.png as example. It's size is 1.3MB, and once 'transformed' by Filepond its size is near to 1.9MB (in Chrome).

Why is the filesize increased by a fair bit while the image is not being transformed? I can't seem to find the reason.

Update: If I also use imageTransformOutputMimeType: 'image/jpeg', the size of the png (now jpeg) is greatly reduced. Is this something which is typical for png?

**Comment by rikschennink** [comment]
The `imageTransformOutputQuality` only applies to JPEGs as PNG quality cannot be set. In this case FilePond will re-save the PNG which depending on the browser can result in a bigger file.

**Comment by RenoLooijmans** [comment]
Thanks for the clarification. This explains alot why it is working as it is.
