### ISSUE TITLE
Adding EXIF orientation plugin renders incorrect output for camera images

### ISSUE THREAD

**Issue by ChrisH91** [pqina/filepond-plugin-image-transform#5]
When adding the EXIF orientation plugin images that are uploaded to the server are sent without being reoriented and with a black bar across part of the image.

The image preview and image editor display the image correctly, it's only the uploaded output that has the issues. Only images with EXIF orientation data are affected.

Image editor view:
![screenshot_20181025-134513](https://user-images.githubusercontent.com/1367413/47529410-9698fe80-d85c-11e8-98b6-68908c1f0307.png)

Uploaded image:
![uploaded](https://user-images.githubusercontent.com/1367413/47529414-9862c200-d85c-11e8-9be5-be88d3c37f5b.jpg)

**Comment by rikschennink** [comment]
Found the issue working on a fix.

**Comment by rikschennink** [comment]
Just publish version `3.0.3` of the image transform plugin, should fix the problem, let me know.

**Comment by benediktwerner** [comment]
I just noticed the same issue and updated the plugin and it seems to work now. Thanks for the quick fix!
