### ISSUE TITLE
No format specified for Image error on request

### ISSUE THREAD

**Issue by newtriks** [pqina/filepond-plugin-image-transform#7]
I upgraded today from version `3.2.4` to `3.3.1.` and file uploads are now failing with the following HTTP response error: _No format specified for Image_. I can get a working example if need be but I'm not really doing anything that deviates dramatically from the docs. The only other plugin I am using is `filepond-plugin-image-exif-orientation` and all versions are the latest and greatest.

**Comment by rikschennink** [comment]
Can you paste your options? Are you using a custom backend? Or the PHP boilerplate?

**Comment by rikschennink** [comment]
I'm sure something is up, but I can't reproduce it.

**Comment by newtriks** [comment]
@rikschennink a custom back end.

```
//
registerPlugin(FilePondPluginImageExifOrientation, FilePondPluginImageTransform)
//
@bind
  handleProcessing(fieldName, file, metadata, load, error, progress, abort) {
    // Call POST fetch function to upload file
    api
      .uploadFile({
        // Build FormData adding file and session data
        files: utils.formData(file, tempSessionData),
      })
      .then(response => {
        // Call for Filepond to handle loaded image
        load(response.clientfilename)
        // Add image to canvas
        this.props.onClick('addImage', response)
        // Hide the component
        this.setState({ show: false })
      })
      .catch(err => {
        // Call for Filepond to handle error
        error(err)
      })
    return {
      abort: () => {
        // Call for Filepond to handle abort (user cancelled)
        abort()
      },
    }
  }
//
<FilePond
          dropOnPage
          dropOnElement={false}
          server={{
            process: this.handleProcessing,
          }}
        />
```

**Comment by rikschennink** [comment]
What does the POST request look like in the network tab (request headers / body), also, if you log the `file` object in the processing method, what does it show in the console.

**Comment by rikschennink** [comment]
Closed because no response since May 25th
