### ISSUE TITLE
How to use original image when transformed image end up being larger in size

### ISSUE THREAD

**Issue by joonhocho** [pqina/filepond-plugin-image-transform#8]
If you try to compress [this very long png](https://www.google.com/search?q=longest+image&newwindow=1&safe=off&rlz=1C5CHFA_enUS812US812&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiwtPDakpjjAhXXWc0KHaIeA70Q_AUIECgB&biw=1280&bih=1312&dpr=1#imgrc=vBPwng9CuNz6EM:), its size changes from 2MB to 7.3MB (3.6 times of original).

In these cases, I would like to upload original instead for obvious reasons.

Is this currently possible?

Or choose to transform only jpeg files, because I think png files are often better untouched.

**Comment by rikschennink** [comment]
Is the result the same on different browsers?

**Comment by joonhocho** [comment]
@rikschennink It happens on latest Chrome as far as I tested.

**Comment by rikschennink** [comment]
@joonhocho Have you tested other browsers?

**Comment by rikschennink** [comment]
Closed because no response since July 4th

**Comment by RenoLooijmans** [comment]
Hi,

I'm more or less experiencing the same issue as mentioned in the initial post. I have the following options enabled:

allowImageTransform: true,
imageTransformOutputQuality: 20,
imageTransformOutputQualityMode: 'optional',
allowImageResize: true,
allowImageCrop: true,
imageResizeMode: 'cover',
// some other values

When I upload a PNG file of filesize 1.73MB, which is exactly the given size (and thus no transform is applied, I assume), it ends up being around 2.1MB Chrome and 2.2MB in Firefox.

Changing the imageTransformOutputQuality does not seem to result in any changes in filesize or image quality.

Please note the image in question is compressed in Photoshop using the option 'slowest/smallest'.

See https://renolooijmans.nl/public/file_example.png as example. It's size is 1.3MB, and once 'transformed' by Filepond its size is near to 1.9MB (in Chrome).

I'm pulling hairs now, what could I be doing wrong?
