### ISSUE TITLE
imageTransformOutputQuality value after create

### ISSUE THREAD

**Issue by kimlambiguit** [pqina/filepond-plugin-image-transform#9]
I'm currently trying to find a way to set the imageTransformOutputQuality to a calculated value. the example in this page shows that you can only set it on FilePond.create(). I would like to:

Calculate the value for imageTransformOutputQuality based on the image's file size. for example.
If my max file size is 1mb, and i have a 20mb image. the percentage would be

pctAdjustment = (1/20) * 100; //5%

is this possible?

**Comment by rikschennink** [comment]
Quality is set for all files in the list, not per file, so that's not possible.

You can fork the plugin and edit the code.

**Comment by rikschennink** [comment]
closed because inactive
